"""
AnalyticsAgent — registered as intent 'analytics'.
Auto-generated by agentforge.
"""
from typing import Any, Dict

from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_core.tools import tool

from agents.base_agent import BaseAgent
from agents.registry import AgentRegistry
from observability.logging import get_logger
from observability.tracing import observe

logger = get_logger(__name__)

# ── Tool definitions ────────────────────────────────────────────────
@tool
def generate_chart(query: str) -> str:
    """Generate a chart from data"""
    # TODO: implement generate_chart
    raise NotImplementedError
@tool
def run_analysis(query: str) -> str:
    """Run statistical analysis on data"""
    # TODO: implement run_analysis
    raise NotImplementedError

_TOOLS = [generate_chart, run_analysis, ]


@AgentRegistry.register("analytics")
class AnalyticsAgent(BaseAgent):

    @property
    def name(self) -> str:
        return "analytics"

    @property
    def needs_validation(self) -> bool:
        return False

    @observe(name="analytics_agent_run")
    def run(self, query: str) -> Dict[str, Any]:
        """
        Basic single-shot LLM call with tool bindings. Replace with a
        tool-calling loop (e.g., langgraph's create_react_agent) when you
        need iterative tool use.
        """
        llm = ChatOpenAI(model="LLMModel.CLAUDE_3_5", temperature=0)
        if _TOOLS:
            llm = llm.bind_tools(_TOOLS)
        messages = [
            SystemMessage(content="""You are an analytics assistant that helps users analyze data.
Focus on providing insights and visualizations.
"""),
            HumanMessage(content=query),
        ]
        try:
            response = llm.invoke(messages)
            return {
                "success": True,
                "output": getattr(response, "content", str(response)),
                "error": None,
            }
        except Exception as exc:
            logger.exception("AnalyticsAgent.run failed")
            return {"success": False, "output": "", "error": str(exc)}