"""
DataAgent — registered as intent 'data'.
Auto-generated by agentforge.
"""
from typing import Any, Dict

from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_core.tools import tool

from agents.base_agent import BaseAgent
from agents.registry import AgentRegistry
from observability.logging import get_logger
from observability.tracing import observe

logger = get_logger(__name__)

# ── Tool definitions ────────────────────────────────────────────────
@tool
def execute_sql(query: str) -> str:
    """Run a SQL query against the database"""
    # TODO: implement execute_sql
    raise NotImplementedError
@tool
def describe_table(query: str) -> str:
    """Get the schema of a database table"""
    # TODO: implement describe_table
    raise NotImplementedError

_TOOLS = [execute_sql, describe_table, ]


@AgentRegistry.register("data")
class DataAgent(BaseAgent):

    @property
    def name(self) -> str:
        return "data"

    @property
    def needs_validation(self) -> bool:
        return True

    @observe(name="data_agent_run")
    def run(self, query: str) -> Dict[str, Any]:
        """
        Basic single-shot LLM call with tool bindings. Replace with a
        tool-calling loop (e.g., langgraph's create_react_agent) when you
        need iterative tool use.
        """
        llm = ChatOpenAI(model="LLMModel.GPT4O", temperature=0)
        if _TOOLS:
            llm = llm.bind_tools(_TOOLS)
        messages = [
            SystemMessage(content="""You are a data analyst with access to database tools via MCP.
Always validate queries before executing them.
"""),
            HumanMessage(content=query),
        ]
        try:
            response = llm.invoke(messages)
            return {
                "success": True,
                "output": getattr(response, "content", str(response)),
                "error": None,
                "query": None,
                "execution_time": None,
            }
        except Exception as exc:
            logger.exception("DataAgent.run failed")
            return {"success": False, "output": "", "error": str(exc)}